### ISSUE TITLE
UI position shifted

### ISSUE THREAD

**Issue by hatelove** [CodeConnect/AliveFeedback#42]
Here is my sample code: https://gist.github.com/hatelove/77ea93fdf863d58a28f0

I wrote some code and the value of variables look like shifted.
![ui position](https://cloud.githubusercontent.com/assets/1528587/10048447/7d6c5f64-6245-11e5-8cc7-e4142a428e41.jpg)

version: VS2015 + Alive 0.6.1

**Comment by AmadeusW** [comment]
Thank you for feedback. We will investigate this issue.
Do you remember what triggered the shift? Did you cut or paste some code?

**Comment by hatelove** [comment]
I record a sample code to reproduce this situation: https://youtu.be/jBj9m1E4-9A

and I got output information:

---

[Message] Using MSTest framework discovery adapter to discover tests in PositionShiftedOfUI. 
[Performance, TestDiscovery, Message] 2015-09-23 16:12:31Z - Test case discovery - 103 ms. 
[Error, Pipeline] There were errors instrumenting your code. 
[Error, Pipeline]  -> Compilation errors in project PositionShiftedOfUI 
[Error, Pipeline] System.ApplicationException: Compilation errors in project PositionShiftedOfUI
   at CodeConnect.ExecutionEngine.AssemblyHelper.handleCompilationErrorsAndThrow(ImmutableArray`1 diagnostics, String projectName)
   at CodeConnect.ExecutionEngine.AssemblyHelper.emitProjectToDisk(Project project, String outputDirectory)
   at CodeConnect.ExecutionEngine.AssemblyHelper.EmitAssembliesForProject(Project project, String outputDirectory)
   at CodeConnect.ProjectOrange.Pipeline.<Run>d__39.MoveNext() 
[Error, TestDiscovery] CS0103 at UnitTest1.cs line 31 (character 81): The name 'length' does not exist in the current context

[Error, Pipeline] Alive encountered an error running GetFoo. Stopping Alive. 
[Error, Pipeline]  -> Object reference not set to an instance of an object. 
[Error, Pipeline] System.NullReferenceException: Object reference not set to an instance of an object.
   at CodeConnect.ExecutionEngine.SolutionTracker.<GetRewrittenDocumentAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at CodeConnect.ProjectOrange.Pipeline.<Run>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CodeConnect.ProjectOrange.Pipeline.<Process>d__38.MoveNext() 
[Message] Code threw exception AssertFailedException: Assert.IsTrue failed.  

---

my for loop's scroll bar disappeared.

**Comment by JoshVarty** [comment]
I can reproduce this. Thanks so much for the code, it makes it much easier to debug!

I'll be investigating this over the weekend.

**Comment by JoshVarty** [comment]
Good news, I should have this fixed. It should make it into our weekly release this Wednesday. :)

![image](https://i.gyazo.com/18e278d5eb58c4f069caa2e4ef4103c6.gif)

**Comment by hatelove** [comment]
Thanks for your quickly action, @JoshVarty . I would like to try my best to report the issues in action and make Alive better.

**Comment by hatelove** [comment]
It seems like if I generate a class in the same file, the UI position will be shifted. If I generate class in the new file, it'll be okay.

**Comment by JoshVarty** [comment]
That's right, I found the same issue when I was fixing this. I've changed our code so it will work even when the class is in the same file. :)

**Comment by AmadeusW** [comment]
@hatelove thank you for reporting this bug!
We've fixed this in [v 0.6.3](https://github.com/CodeConnect/AliveFeedback/wiki/Changelog-0.6.3) :smiley:
