### ISSUE TITLE
[Error, Pipeline]Access denied with System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by hatelove** [CodeConnect/AliveFeedback#43]
I couldn't find my test by Enable AutoFilter, so I filter by search text and launch my test case.Then I got a error infomation on my output window:

```
[Error, Pipeline]  -> Access to the path 'C:\Users\myaccount\AppData\Local\Temp\Alive\bin\Logistic.Test\Logistic.Test.config' is denied. 
[Error, Pipeline] System.UnauthorizedAccessException: Access to the path 'C:\Users\myaccount\AppData\Local\Temp\Alive\bin\Logistic.Test\Logistic.Test.config' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at CodeConnect.ExecutionEngine.AssemblyHelper.copyConfigFile(Project project, String projectOutputDirectory)
   at CodeConnect.ExecutionEngine.AssemblyHelper.emitProjectToDisk(Project project, String outputDirectory)
   at CodeConnect.ExecutionEngine.AssemblyHelper.EmitAssembliesForProject(Project project, String outputDirectory)
   at CodeConnect.ProjectOrange.Pipeline.<Run>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CodeConnect.ProjectOrange.Pipeline.<Process>d__43.MoveNext() 
```

My test project assembly is "Logistic.Test", Alive version: 0.6.2 and I run Visual Studio 2015 as admin

**Comment by JoshVarty** [comment]
Thanks @hatelove, we'll look into this. It looks like there might be issues with multiple processes trying to access that file.

**Comment by hatelove** [comment]
got it, I'll check if cause by the other extensions .

**Comment by AmadeusW** [comment]
@hatelove did you have two Visual Studios open, and loaded either the same solution, or different solutions that share a project?

**Comment by hatelove** [comment]
@AmadeusW , in my case, I only open a Visual Studio and one solution. I'll try to disable other visual studio extensions to check if they cause.

**Comment by AmadeusW** [comment]
@hatelove are you using some antivirus software? I suspect that it may set a lock on files that newly appear on the hard drive, and the file in question is one of them.

**Comment by hatelove** [comment]
@AmadeusW, yes, symantic and my windows is company's image that I couldn't disable it. I'll find the other one to try it. 

If I created new project and developed with Alive, there are no any problem bothered me. But when I open the exist or some big project (like with over 400 test cases and some of them are integration test with database), Alive will hang or get some problems like access authorized failed.
